version: "3.7"

services:
  mysql:
    #platform: linux/amd64
    container_name: klarnapayment-mysql-1784
    image: mysql:5.7
    ports:
      - "9002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -uroot -pprestashop --silent"
      interval: 10s
    networks:
      - prestashop_klarnapayment_net_1784

  prestashop-17:
    #platform: linux/amd64
    container_name: prestashop-1784
    build:
      context: .
      dockerfile: .docker/Dockerfile.1784
    environment:
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      PS_DOMAIN: klarnapayment1784.ngrok.io
      PS_FOLDER_INSTALL: install
      PS_FOLDER_ADMIN: admin1
    depends_on:
      - mysql
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/modules/klarnapayment
      - ./.docker/.htaccess1784:/var/www/html/.htaccess
    networks:
      - prestashop_klarnapayment_net_1784
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"
      interval: 10s

  adminer:
    image: adminer
    restart: always
    ports:
      - '6969:8080'
    networks:
      - prestashop_klarnapayment_net_1784

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - prestashop_klarnapayment_net_1784

networks:
  prestashop_klarnapayment_net_1784:
    name: 'prestashop_klarnapayment_net_1784'
