version: "3.7"

services:
  mysql:
    platform: linux/amd64
    container_name: mysql-klarnapayment-8
    image: mysql:5.7
    ports:
      - "9459:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -uroot -pprestashop --silent"
      interval: 10s
    networks:
      - prestashop_klarnapayment_net_8
  prestashop-8:
    platform: linux/amd64
    container_name: prestashop-klarnapayment-8
    build:
      context: .
      dockerfile: .docker/Dockerfile.8
    environment:
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      PS_DOMAIN: klarnapayment8.ngrok.io
      PS_FOLDER_INSTALL: install
      PS_FOLDER_ADMIN: admin1
    depends_on:
      - mysql
    ports:
      - "8142:80"
    volumes:
      - ./:/var/www/html/modules/klarnapayment
      - ./.docker/.htaccess8:/var/www/html/.htaccess
    networks:
      - prestashop_klarnapayment_net_8
    healthcheck:
      test: "curl -f localhost:8142"
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - '6969:8080'
    networks:
      - prestashop_klarnapayment_net_8

networks:
  prestashop_klarnapayment_net_8:
    name: 'prestashop_klarnapayment_net_8'
